services:
  - type: web
    name: gestus-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app --timeout 120 --workers 1 --max-requests 1000 --max-requests-jitter 50
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MODEL_PATH
        value: best_model.pth
      - key: SUPABASE_URL
        value: https://bctfiwwbascthdbttavj.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdGZpd3diYXNjdGhkYnR0YXZqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NjY0MTA5NiwiZXhwIjoyMDYyMjE3MDk2fQ.foFL5AtIBhnitzKaot2xNJuR4mwVO046ttktYIiwXTs
      - key: SUPABASE_BUCKET
        value: libras-dataset
